import type { GitHubClient } from "@fairygitmother/core";
import { eq } from "drizzle-orm";
import { emitEvent } from "../api/feed.js";
import { logAudit } from "../audit.js";
import type { FairygitMotherDb } from "../db/client.js";
import { bounties, consensusResults, submissions } from "../db/schema.js";

export interface PrSubmission {
	prNumber: number;
	prUrl: string;
}

export function buildPrBody(
	_bountyOwner: string,
	_bountyRepo: string,
	issueNumber: number,
	explanation: string,
	solverNodeId: string,
	solverBackend: string,
	approveCount: number,
	totalVotes: number,
): string {
	return `## Automated Fix

Fixes #${issueNumber}

${explanation}

---

> This PR was generated by [FairygitMother](https://github.com/buildepicshit/FairygitMother), a distributed agent grid for open source maintenance.
> - Solver: \`${solverNodeId}\` (${solverBackend})
> - Reviewed by: ${totalVotes} independent agents
> - Consensus: ${approveCount}/${totalVotes} approved
>
> To opt out, add \`fairygitmother: false\` to your repo config or close this PR.`;
}

export async function submitPr(
	db: FairygitMotherDb,
	github: GitHubClient,
	submissionId: string,
	forkOwner: string,
): Promise<PrSubmission | null> {
	const consensus = db
		.select()
		.from(consensusResults)
		.where(eq(consensusResults.submissionId, submissionId))
		.get();
	if (!consensus || consensus.outcome !== "approved") return null;

	const submission = db.select().from(submissions).where(eq(submissions.id, submissionId)).get();
	if (!submission) return null;

	const bounty = db.select().from(bounties).where(eq(bounties.id, submission.bountyId)).get();
	if (!bounty) return null;

	const branchName = `fairygitmother/fix-${bounty.issueNumber}-${submission.id.slice(0, 8)}`;

	const body = buildPrBody(
		bounty.owner,
		bounty.repo,
		bounty.issueNumber,
		submission.explanation,
		submission.nodeId,
		submission.solverBackend,
		consensus.approveCount,
		consensus.totalVotes,
	);

	const pr = await github.createPullRequest(
		bounty.owner,
		bounty.repo,
		`${forkOwner}:${branchName}`,
		"main",
		`fix: ${bounty.issueTitle} (#${bounty.issueNumber})`,
		body,
	);

	// Update consensus with PR URL
	db.update(consensusResults)
		.set({ prUrl: pr.html_url })
		.where(eq(consensusResults.id, consensus.id))
		.run();

	// Update bounty status
	db.update(bounties)
		.set({ status: "pr_submitted", updatedAt: new Date().toISOString() })
		.where(eq(bounties.id, bounty.id))
		.run();

	emitEvent({
		type: "pr_submitted",
		bountyId: bounty.id,
		prUrl: pr.html_url,
	});
	logAudit(db, "pr_submitted", submissionId, {
		bountyId: bounty.id,
		prUrl: pr.html_url,
		prNumber: pr.number,
	});

	return { prNumber: pr.number, prUrl: pr.html_url };
}
