import type { GitHubClient } from "@fairygitmother/core";
import { eq } from "drizzle-orm";
import { emitEvent } from "../api/feed.js";
import { logAudit } from "../audit.js";
import type { FairygitMotherDb } from "../db/client.js";
import { bounties, consensusResults, submissions } from "../db/schema.js";
import { applyPatch, parseDiff } from "./diff.js";

export interface PrSubmission {
	prNumber: number;
	prUrl: string;
}

export function buildPrBody(
	_bountyOwner: string,
	_bountyRepo: string,
	issueNumber: number,
	explanation: string,
	solverNodeId: string,
	solverBackend: string,
	approveCount: number,
	totalVotes: number,
): string {
	return `## Automated Fix

Fixes #${issueNumber}

${explanation}

---

> This PR was generated by [FairygitMother](https://github.com/buildepicshit/FairygitMother), a distributed agent grid for open source maintenance.
> - Solver: \`${solverNodeId}\` (${solverBackend})
> - Reviewed by: ${totalVotes} independent agents
> - Consensus: ${approveCount}/${totalVotes} approved
>
> To opt out, add \`fairygitmother: false\` to your repo config or close this PR.`;
}

/**
 * Create a branch on the fork with the diff applied, then open a PR to upstream.
 *
 * Flow:
 * 1. Fork the repo (idempotent — reuses existing fork)
 * 2. Sync fork's default branch to upstream HEAD
 * 3. Parse the unified diff into per-file changes
 * 4. For each file: fetch original content, apply patch, create blob
 * 5. Create tree → commit → branch ref on the fork
 * 6. Create PR from fork:branch to upstream:main
 */
export async function submitPr(
	db: FairygitMotherDb,
	github: GitHubClient,
	submissionId: string,
	forkOwner: string,
): Promise<PrSubmission | null> {
	const consensus = (
		await db.select().from(consensusResults).where(eq(consensusResults.submissionId, submissionId))
	)[0];
	if (!consensus || consensus.outcome !== "approved") return null;

	const submission = (
		await db.select().from(submissions).where(eq(submissions.id, submissionId))
	)[0];
	if (!submission) return null;

	const bounty = (await db.select().from(bounties).where(eq(bounties.id, submission.bountyId)))[0];
	if (!bounty) return null;

	const branchName = `fairygitmother/fix-${bounty.issueNumber}-${submission.id.slice(0, 8)}`;

	// 1. Fork the repo (idempotent)
	await github.createFork(bounty.owner, bounty.repo);

	// 2. Get upstream HEAD SHA
	const headSha = await github.getRef(bounty.owner, bounty.repo, "heads/main");
	const { treeSha: baseTreeSha } = await github.getCommit(bounty.owner, bounty.repo, headSha);

	// 3. Parse the diff
	const fileDiffs = parseDiff(submission.diff);
	if (fileDiffs.length === 0) return null;

	// 4. For each file: fetch original, apply patch, collect new content
	const fileChanges: Array<{ path: string; content: string }> = [];
	for (const fileDiff of fileDiffs) {
		const path = fileDiff.isNew ? fileDiff.newPath : fileDiff.oldPath;
		let original = "";
		if (!fileDiff.isNew) {
			original = await github.getFileContent(bounty.owner, bounty.repo, path, headSha);
		}
		const newContent = applyPatch(original, fileDiff.hunks, fileDiff.isNew, fileDiff.isDeleted);
		if (!fileDiff.isDeleted) {
			fileChanges.push({ path, content: newContent });
		}
	}

	// 5. Create tree, commit, and branch on the fork
	const newTreeSha = await github.createTree(forkOwner, bounty.repo, baseTreeSha, fileChanges);
	const commitMessage = `fix: ${bounty.issueTitle} (#${bounty.issueNumber})\n\nFixes #${bounty.issueNumber}\n\nGenerated by FairygitMother`;
	const newCommitSha = await github.createCommitOnRepo(
		forkOwner,
		bounty.repo,
		commitMessage,
		newTreeSha,
		[headSha],
	);
	await github.createRefOnRepo(forkOwner, bounty.repo, `refs/heads/${branchName}`, newCommitSha);

	// 6. Create the PR
	const body = buildPrBody(
		bounty.owner,
		bounty.repo,
		bounty.issueNumber,
		submission.explanation,
		submission.nodeId,
		submission.solverBackend,
		consensus.approveCount,
		consensus.totalVotes,
	);

	const pr = await github.createPullRequest(
		bounty.owner,
		bounty.repo,
		`${forkOwner}:${branchName}`,
		"main",
		`fix: ${bounty.issueTitle} (#${bounty.issueNumber})`,
		body,
	);

	// 7. Update DB
	await db
		.update(consensusResults)
		.set({ prUrl: pr.html_url })
		.where(eq(consensusResults.id, consensus.id));

	await db
		.update(bounties)
		.set({ status: "pr_submitted", updatedAt: new Date().toISOString() })
		.where(eq(bounties.id, bounty.id));

	emitEvent({
		type: "pr_submitted",
		bountyId: bounty.id,
		prUrl: pr.html_url,
	});
	await logAudit(db, "pr_submitted", submissionId, {
		bountyId: bounty.id,
		prUrl: pr.html_url,
		prNumber: pr.number,
	});

	return { prNumber: pr.number, prUrl: pr.html_url };
}
